# Generated by Django 3.2.13 on 2022-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpackApp', '0002_alter_sale_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
